<?php

use Illuminate\Database\Seeder;

class TopListsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // factory(App\Models\TopList::class, 30)->create();
        DB::table('top_lists')->insert([
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 1,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 1,        
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 1,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 2,   
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 1,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 3,   
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 1,
                'subCategory_id' => 1,
                'tweet__id' => 1,      
                'number' => 4,  
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 1,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 5,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 2,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 1,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 2,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 2,        
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 2,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 3,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 2,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 4,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 2,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 5,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 3,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 1,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 3,
                'subCategory_id' => 1,
                'tweet__id' => 1,        
                'number' => 2,   
            ],

            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 3,
                'subCategory_id' => 1,
                'tweet__id' => 1,        
                'number' => 3,   
            ],

            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 3,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 4,          
            ],

            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 3,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 5,           
            ],

            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 4,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 1,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 4,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 2,          
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 4,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 3,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 4,
                'subCategory_id' => 1,
                'tweet__id' => 1,        
                'number' => 4,   
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 4,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 5,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 5,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 1,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 5,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 2,           
            ],

            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 5,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 3,           
            ],

            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 5,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 4,   
            ],

            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 5,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 5,           
            ],

            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 6,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 1,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 6,
                'subCategory_id' => 1,
                'tweet__id' => 1,        
                'number' => 2,   
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 6,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 3,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 6,
                'subCategory_id' => 1,
                'tweet__id' => 1,
                'number' => 4,           
            ],
            [
                'user_id' => 1,
                'content' => 'a',
                'count' => 1,
                'category_id' => 6,
                'subCategory_id' => 1,
                'tweet__id' => 1,        
                'number' => 5,   
            ],
        ]);
    }
}
